export const SET_USER = 'SET_USER';
export const SET_ROLES = 'SET_ROLES';
export const SET_THEME = 'SET_THEME';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_ADDRESSES = 'SET_ADDRESSES';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_TOTAL = 'SET_TOTAL';
export const SET_FETCH_STATE = 'SET_FETCH_STATE';
export const SET_LIMIT = 'SET_LIMIT';
export const SET_OFFSET = 'SET_OFFSET';
export const SET_FILTER = 'SET_FILTER';

export const SET_CART = 'SET_CART';
export const SET_PAYMENT = 'SET_PAYMENT';
export const SET_ADDRESS = 'SET_ADDRESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const CART_QUANTITY_INCREASE = 'CART_QUANTITY_INCREASE';
export const CART_QUANTITY_DECREASE = 'CART_QUANTITY_DECREASE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SET_SORT = 'SET_SORT';
export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';

export const REMOVE_ITEM ='REMOVE_ITEM';
export const TOGGLE_SELECT_ITEM = 'TOGGLE_SELECT_ITEM';